# Generated by Django 4.2.23 on 2025-07-07 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Backlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Create', 'Создана'), ('Accepted', 'Принята'), ('In_test', 'В тесте'), ('Done', 'Выполнена')], max_length=16)),
                ('text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='backlog_attachments/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'бэклог',
                'verbose_name_plural': 'Бэклог',
                'ordering': ('theme',),
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'Группы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('color', models.CharField(choices=[('Blue', 'Голубой'), ('Gray', 'Серый'), ('Green', 'Зеленый'), ('Red', 'Красный'), ('Yellow', 'Желтый')], max_length=16)),
            ],
            options={
                'verbose_name': 'тег',
                'verbose_name_plural': 'Теги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='comment_attachments/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backlog.backlog', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='backlog',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backlog.group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='backlog',
            name='tags',
            field=models.ManyToManyField(to='backlog.tag', verbose_name='Тег'),
        ),
    ]
