# Generated by Django 4.2.23 on 2025-07-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backlog',
            name='status',
            field=models.CharField(choices=[('Create', 'Создана'), ('Accepted', 'Принята'), ('In_test', 'В тесте'), ('Done', 'Выполнена')], default=1, max_length=16),
            preserve_default=False,
        ),
    ]
