# Generated by Django 4.2.23 on 2025-07-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backlog',
            options={'ordering': ('id',), 'verbose_name': 'бэклог', 'verbose_name_plural': 'Бэклог'},
        ),
        migrations.RemoveField(
            model_name='backlog',
            name='attachment',
        ),
        migrations.CreateModel(
            name='BacklogAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='backlog_attachments/')),
                ('backlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='backlog.backlog')),
            ],
        ),
    ]
