# Generated by Django 4.2.23 on 2025-07-03 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backlog',
            options={'ordering': ('theme',), 'verbose_name': 'бэклог', 'verbose_name_plural': 'Бэклог'},
        ),
    ]
