# Generated by Django 4.2.23 on 2025-07-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0002_alter_backlog_options_remove_backlog_attachment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backlogattachment',
            options={'ordering': ('id',), 'verbose_name': 'вложения к задачам', 'verbose_name_plural': 'Вложения к задачам'},
        ),
    ]
