# Generated by Django 4.2.23 on 2025-07-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0003_alter_backlogattachment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='attachment',
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='comment_attachments/')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='backlog.comment')),
            ],
            options={
                'verbose_name': 'вложения к комментариям',
                'verbose_name_plural': 'Вложения к комментариям',
                'ordering': ('id',),
            },
        ),
    ]
