# Generated by Django 4.2.23 on 2025-07-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0004_remove_comment_attachment_commentattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlogattachment',
            name='file',
            field=models.FileField(upload_to='media/backlog_attachments/'),
        ),
        migrations.AlterField(
            model_name='commentattachment',
            name='file',
            field=models.FileField(upload_to='media/comment_attachments/'),
        ),
    ]
