# Generated by Django 4.2.23 on 2025-07-11 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0005_alter_backlogattachment_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='status',
            field=models.CharField(choices=[('Create', 'Создана'), ('Accepted', 'Принята'), ('In_test', 'В тесте'), ('Done', 'Выполнена')], max_length=16, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='backlog',
            name='theme',
            field=models.CharField(max_length=100, verbose_name='Тема'),
        ),
        migrations.AlterField(
            model_name='backlogattachment',
            name='backlog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='backlog.backlog', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='backlogattachment',
            name='file',
            field=models.FileField(upload_to='media/backlog_attachments/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='commentattachment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='backlog.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='commentattachment',
            name='file',
            field=models.FileField(upload_to='media/comment_attachments/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('Blue', 'Голубой'), ('Gray', 'Серый'), ('Green', 'Зеленый'), ('Red', 'Красный'), ('Yellow', 'Желтый')], max_length=16, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=16, verbose_name='Наименование'),
        ),
    ]
