services:

  postgres:
    image: postgres:17.5
    container_name: monitor_postgres
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: monitor_redis
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data

  monitor:
    build: ./monitor
    container_name: monitor
    restart: always
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - ./monitor:/app
      - ./frontend/build:/app/build

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    env_file:
      - .env
    depends_on:
      - monitor
    ports:
      - "4000:3000"
    volumes:
      - ./frontend/src:/app/src  # Только исходники
      - ./frontend/public:/app/public  # Только статика

volumes:
  redis_data:
  monitor_data:
  postgres_data: