services:

  postgres:
    image: postgres:17.5
    container_name: monitor_postgres
    environment:
      POSTGRES_DB: monitor_db
      POSTGRES_USER: django
      POSTGRES_PASSWORD: your_secure_password_here
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  monitor:
    build: ./monitor
    container_name: monitor
    restart: always
    env_file:
      - .env
    ports:
      - "4000:8000"
    volumes:
      - monitor_data:/app
  
  redis:
    image: redis:latest
    container_name: monitor_redis
    restart: always
    ports:
      - "6378:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  monitor_data:
  postgres_data: