services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: monitor_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
