# Generated by Django 4.2.23 on 2025-07-11 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('code', models.TextField(verbose_name='Код')),
                ('variables', models.JSONField(blank=True, default=dict, verbose_name='Переменные для подстановки')),
                ('output', models.TextField(blank=True, null=True, verbose_name='Вывод программы')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Ошибки выполнения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'код сообщений',
                'verbose_name_plural': 'Код сообщений',
                'ordering': ('id',),
            },
        ),
    ]
