# Generated by Django 4.2.23 on 2025-07-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSHHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('port', models.IntegerField(default=22)),
                ('button_change_base', models.BooleanField(default=False)),
                ('button_dump_pg', models.BooleanField(default=False)),
                ('docker_base', models.CharField(max_length=100)),
                ('docker_prod', models.CharField(max_length=100)),
                ('button_fast_pull', models.BooleanField(default=False)),
                ('button_pull_reload', models.BooleanField(default=False)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('last_commit', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'сервер',
                'verbose_name_plural': 'Серверы',
            },
        ),
    ]
