# Generated by Django 4.2.23 on 2025-06-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshhost',
            name='docker_base',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sshhost',
            name='docker_prod',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
