# Generated by Django 5.2.3 on 2025-07-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshhost',
            name='last_commit',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sshhost',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
