# Generated by Django 4.2.23 on 2025-07-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshhost',
            name='commit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
