# Generated by Django 4.2.23 on 2025-06-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sshhost_docker_base_sshhost_docker_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshhost',
            name='button_change_base',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
