# Generated by Django 4.2.23 on 2025-06-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sshhost_button_change_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshhost',
            name='button_dump_pg',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
