# Generated by Django 4.2.23 on 2025-06-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sshhost_button_dump_pg'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshhost',
            name='button_fast_pull',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sshhost',
            name='button_pull_reload',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sshhost',
            name='button_change_base',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sshhost',
            name='button_dump_pg',
            field=models.BooleanField(default=False),
        ),
    ]
